services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    ports:
      - "3307:3306"
    env_file:
      - ./.env
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    image: 061039790334.dkr.ecr.us-west-1.amazonaws.com/frontend:latest
    container_name: frontend
    ports:
      - "${FRONTEND_PORT:-3001}:${FRONTEND_PORT:-3001}"
    depends_on:
      - backend
    env_file:
      - ./.env

  backend:
    image: 061039790334.dkr.ecr.us-west-1.amazonaws.com/frontend:latest
    container_name: backend
    ports:
      - "${BACKEND_PORT:-3002}:${BACKEND_PORT:-3002}"
    env_file:
      - ./.env

  nginx:
    image: nginx:1.25
    container_name: nginx
    ports:
      - "3000:3000"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
