# This is a basic workflow to help you get started with Actions

name: Nightly Build

# Controls when the workflow will run
on:
  # Triggers nightly
  schedule:
    - cron: "0 8 * * *" # 12am PST 8am UTC

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Check out source repo
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          repository: ielo03/qc-devops-source
          token: ${{ secrets.GITHUB_TOKEN }}
          path: source

      - name: List contents of source repo
        run: ls -la source
