name: Test

on:
  workflow_dispatch:

jobs:
  Terminate-Instance:
    runs-on: Ubuntu-24.04
    if: always()  # This ensures the job runs regardless of previous failures.
    steps:
      - name: Terminate EC2 instance if exists
        run: |
          if [ -n "i-09c61361c04702ded" ]; then
            echo "Terminating EC2 instance i-09c61361c04702ded..."
            aws ec2 terminate-instances --instance-ids i-09c61361c04702ded
          else
            echo "No EC2 instance was launched, failing termination."
            exit 1
          fi
